server:
  port: 8083
  portCatalogService: 8080
  portWalletService: 8082
  portOrderService: 8081

application:
  urlCatalogService: "localhost:8080"
  urlWalletService: "localhost:8082"
  urlOrderService: "localhost:8081"
