server:
  port: 8081
  portCatalogService: 8080
  portWalletService: 8082
  portWarehouseService: 8083

application:
  urlCatalogService: "localhost:8080"
  urlWalletService: "localhost:8082"
  urlWarehouseService: "localhost:8083"
